// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebReceipt.Server.AppDatabaseContext;

#nullable disable

namespace WebReceipt.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240329045348_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebReceipt.Models.NatureOfCollectionModel", b =>
                {
                    b.Property<int>("NatureOfCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NatureOfCollectionId"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("NatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.HasKey("NatureOfCollectionId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("NatureOfCollections");
                });

            modelBuilder.Entity("WebReceipt.Models.ReceiptModel", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fund")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<string>("Value1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("checked1")
                        .HasColumnType("bit");

                    b.Property<bool>("checked2")
                        .HasColumnType("bit");

                    b.Property<bool>("checked3")
                        .HasColumnType("bit");

                    b.HasKey("ReceiptId");

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("WebReceipt.Models.UserAccountModel", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAccountId"));

                    b.Property<string>("UserAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAccountPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserAccountId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("WebReceipt.Models.NatureOfCollectionModel", b =>
                {
                    b.HasOne("WebReceipt.Models.ReceiptModel", null)
                        .WithMany("ListOfNatures")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebReceipt.Models.ReceiptModel", b =>
                {
                    b.Navigation("ListOfNatures");
                });
#pragma warning restore 612, 618
        }
    }
}
